experiment:
  seed_acronym: ACA
  target_regex: '*'
processing:
  aggregation_mode: mean
  metric: projection_density
quality_control:
  min_injection_volume: 0.05
  threshold_lower: 1.0e-05
selection:
  custom_targets:
  - MOp
  - MOs
  - PL
  - SSs
  - VISp
  - RSPd
  use_custom_targets: true
